In [10]:
import pandas as pd 
import numpy as np 
from sklearn.datasets import load_iris 

In [12]:
df = load_iris(as_frame=True).frame

df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [34]:
columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'target']

df.columns = columns 

In [26]:
means = df.mean().values 
stds = df.std().values 

def normalize_data(df): 
    df_copy = df.copy()

    for i, col in enumerate(df_copy.columns): 
        df_copy[col] = (df_copy[col] - means[i]) / stds[i]

    return df_copy 

df_norm = normalize_data(df[columns[:-1]])

df_norm.head()


sepal_length  sepal_width  petal_length  petal_width
0     -0.897674     1.015602     -1.335752    -1.311052
1     -1.139200    -0.131539     -1.335752    -1.311052
2     -1.380727     0.327318     -1.392399    -1.311052
3     -1.501490     0.097889     -1.279104    -1.311052
4     -1.018437     1.245030     -1.335752    -1.311052

In [40]:
# Covariance matrix 
cov_matrix = np.dot(df_norm.T, df_norm) / (df_norm.shape[0] - 1)

print("Covariance Matrix")
print(cov_matrix)

Covariance Matrix
[[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]


In [41]:
# extract eigenvalues and eigen vectors 
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("Eigenvalues:",  eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: [2.91849782 0.91403047 0.14675688 0.02071484]
Eigenvectors: [[ 0.52106591 -0.37741762 -0.71956635  0.26128628]
 [-0.26934744 -0.92329566  0.24438178 -0.12350962]
 [ 0.5804131  -0.02449161  0.14212637 -0.80144925]
 [ 0.56485654 -0.06694199  0.63427274  0.52359713]]
